routes/web.php
<?php

use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\CampaignsController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\WebsitesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/login', [LoginController::class, 'index'])->name('login');
Route::post('/login', [LoginController::class, 'login'])->name('login-attempt');
Route::get('/register', [RegisterController::class, 'index'])->name('register');
Route::post('/register', [RegisterController::class, 'store'])->name('register-store');

Route::middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

    Route::name('websites.')->prefix('websites')->group(function () {
        Route::get('/', [WebsitesController::class, 'index'])->name('index');
        Route::get('/create', [WebsitesController::class, 'create'])->name('create');
        Route::post('/', [WebsitesController::class, 'store'])->name('store');
        Route::get('/{website}/analytics', [WebsitesController::class, 'analytics'])->name('analytics');
        Route::get('/{website}/status/{status}', [WebsitesController::class, 'status'])->name('status');
    });

    Route::name('campaigns.')->prefix('campaigns')->group(function () {
        Route::get('/', [CampaignsController::class, 'index'])->name('index');
        Route::get('/create', [CampaignsController::class, 'create'])->name('create');
        Route::post('/', [CampaignsController::class, 'store'])->name('store');
        Route::get('/{campaign}/status/{status}', [CampaignsController::class, 'status'])->name('status');
    });

    Route::name('analytics.')->prefix('analytics')->group(function () {
        Route::get('/', [AnalyticsController::class, 'index'])->name('index');
        Route::get('/{uuid}', [AnalyticsController::class, 'show'])->name('show');
    });
});

app/Models/Website.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Website extends Model
{
    use HasFactory;
}

app/Http/Controllers/WebsitesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\WebsiteStoreRequest;
use App\Models\Website;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Foundation\Application;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class WebsitesController extends Controller
{
    /**
     * @return View|Application|Factory|\Illuminate\Contracts\Foundation\Application
     */
    public function index(): View|Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $sectionTitle = 'Websites';

        $websites = Website::where('user_id', Auth::id())
            ->orderBy('created_at', 'desc')
            ->paginate(15);

        return view('websites.index')
            ->with('websites', $websites)
            ->with('sectionTitle', $sectionTitle);
    }

    /**
     * @return View|Application|Factory|\Illuminate\Contracts\Foundation\Application
     */
    public function create(): View|Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $sectionTitle = 'Websites - Create';

        return view('websites.create')
            ->with('sectionTitle', $sectionTitle);
    }

    /**
     * @param WebsiteStoreRequest $request
     * @return RedirectResponse
     */
    public function store(WebsiteStoreRequest $request): RedirectResponse
    {
        $website = new Website();
        $website->user_id = Auth::id();
        $website->uuid = Str::uuid();
        $website->name = $request->name;
        $website->url = $request->url;
        $website->save();

        return redirect()->route('websites.index')
            ->with('success', 'You have successfully added new website.');
    }

    /**
     * @param Website $website
     * @param $status
     * @return RedirectResponse
     */
    public function status(Website $website, $status): RedirectResponse
    {
        if($website->user_id != Auth::id()) {
            abort(403);
        }

        if(!in_array($status, ['start', 'stop'])) {
            return redirect()->back()->with('error', 'Wrong status!');
        }

        $website->is_active = $status == 'start';
        $website->save();

        return redirect()->route('websites.index')->with('success', "Status has been successfully updated.");
    }
}

resources/views/websites/create.blade.php
@extends('layouts.master')

@section('content')
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ $sectionTitle }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a href="{{ route('websites.index') }}" class="btn btn-sm btn-secondary"><i class="bi bi-arrow-left-short"></i> Go Back</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-sm-12">
            @include('fragments.alerts')

            <form name="createWebsite" method="POST" action="{{ route('websites.store') }}">
                @csrf
                <div class="mb-3">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" name="name" class="form-control" id="name" placeholder="Website Name" value="{{ old('name') }}">
                </div>
                <div class="mb-3">
                    <label for="url" class="form-label">URL</label>
                    <input type="text" name="url" class="form-control" id="url" placeholder="Website URL" value="{{ old('url') }}">
                </div>
                <div class="mb-3">
                    <label for="description" class="form-label">Description</label>
                    <textarea class="form-control" name="description" id="description" rows="3">{{ old('description') }}</textarea>
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-primary"><i class="bi bi-floppy"></i> Create</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/websites/index.blade.php
@extends('layouts.master')

@section('content')
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ $sectionTitle }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a href="{{ route('websites.create') }}" class="btn btn-sm btn-secondary"><i class="bi bi-folder-plus"></i> Create</a>
            </div>
        </div>
    </div>

    @include('fragments.alerts')
    <div class="table-responsive">
        @if(count($websites) > 0)
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Created At</th>
                    <th scope="col">Status</th>
                    <th scope="col">Name</th>
                    <th scope="col">URL</th>
                    <th scope="col">UUID</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                @foreach($websites as $website)
                    <tr>
                        <td>{{ \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $website->created_at)->format('d/m/Y H:i') }}</td>
                        <td>
                            @if($website->is_active)
                                <a href="/websites/{{ $website->id }}/status/stop" class="btn btn-sm btn-danger"><i class="bi bi-stop-circle"></i> Stop</a>
                            @else
                                <a href="/websites/{{ $website->id }}/status/start" class="btn btn-sm btn-primary"><i class="bi bi-play-fill"></i> Start</a>
                            @endif
                        </td>
                        <td>{{ $website->name }}</td>
                        <td><a target="_blank" href="{{ $website->url }}">{{ $website->url }}</a></td>
                        <td>{{ $website->uuid }}</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Controls">
                                <button data-bs-toggle="modal" data-bs-target="#modal-{{ $website->id }}" class="btn btn-sm btn-success"><i class="bi bi-code-square"></i> Get Code</button>
                                <a href="/analytics?website={{ $website->id }}" class="btn btn-sm btn-warning"><i class="bi bi-clipboard-data"></i> Analytics</a>
                            </div>
                        </td>
                    </tr>

                    <div id="modal-{{ $website->id }}" class="modal" tabindex="-1">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Tracking Code</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <textarea rows="3" class="form-control" readonly><script src="{{ URL::to('/tracker.js?uuid=' . $website->uuid ) }}"></script></textarea>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="bi bi-x-circle"></i> Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
                </tbody>
            </table>

            {{ $websites->links() }}
        @else
            @include('fragments.no-data')
        @endif
    </div>
@endsection