routes/web.php
<?php

use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\CampaignsController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\WebsitesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/login', [LoginController::class, 'index'])->name('login');
Route::post('/login', [LoginController::class, 'login'])->name('login-attempt');
Route::get('/register', [RegisterController::class, 'index'])->name('register');
Route::post('/register', [RegisterController::class, 'store'])->name('register-store');

Route::middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

    Route::name('websites.')->prefix('websites')->group(function () {
        Route::get('/', [WebsitesController::class, 'index'])->name('index');
        Route::get('/create', [WebsitesController::class, 'create'])->name('create');
        Route::post('/', [WebsitesController::class, 'store'])->name('store');
        Route::get('/{website}/analytics', [WebsitesController::class, 'analytics'])->name('analytics');
        Route::get('/{website}/status/{status}', [WebsitesController::class, 'status'])->name('status');
    });

    Route::name('campaigns.')->prefix('campaigns')->group(function () {
        Route::get('/', [CampaignsController::class, 'index'])->name('index');
        Route::get('/create', [CampaignsController::class, 'create'])->name('create');
        Route::post('/', [CampaignsController::class, 'store'])->name('store');
        Route::get('/{campaign}/status/{status}', [CampaignsController::class, 'status'])->name('status');
    });

    Route::name('analytics.')->prefix('analytics')->group(function () {
        Route::get('/', [AnalyticsController::class, 'index'])->name('index');
        Route::get('/{uuid}', [AnalyticsController::class, 'show'])->name('show');
    });
});

resources/views/fragments/alerts.blade.php
<div class="mt-3">
    @if ($errors->any())
        @foreach($errors->all() as $error)
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <i class="bi bi-exclamation-triangle"></i> {{ $error }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endforeach
    @endif

    @if(session()->has('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <i class="bi bi-exclamation-triangle"></i> {{ session()->get('error') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

    @if(session()->has('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <i class="bi bi-hand-thumbs-up"></i> {{ session()->get('success') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

    @if(session()->has('info'))
        <div class="alert alert-info alert-dismissible fade show" role="alert">
            <i class="bi bi-info-circle"></i> {{ session()->get('info') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

    @if(session()->get('warning'))
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <i class="bi bi-exclamation-square"></i> {{ session()->get('warning') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif
</div>

resources/views/fragments/logs.blade.php
<div class="row mt-4">
    <div class="col">
        <h4><i class="bi bi-activity"></i> {{ $title }}</h4>
        <div class="table-responsive">
            @if(count($logs) > 0)
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Last Record</th>
                        <th scope="col">Website</th>
                        <th scope="col">Campaign</th>
                        <th scope="col">Session</th>
                        <th scope="col">IP</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($logs as $log)
                        <tr>
                            <td>{{ \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $log->recorded_at)->format('d/m/Y H:i') }}</td>
                            <td>{{ $log->website_name }} - {{ $log->website_url }}</td>
                            <td>{{ !empty($log->campaign_name) ? $log->campaign_name : 'n/a' }}</td>
                            <td>{{ $log->uuid }}</td>
                            <td>{{ $log->ip }}</td>
                            <td>
                                <a href="{{ route('analytics.show' , ['uuid' => $log->uuid]) }}" class="btn btn-sm btn-success"><i class="bi bi-eye"></i> View</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

                @if($pagination)
                    {{ $logs->links() }}
                @endif
            @else
                @include('fragments.no-data')
            @endif
        </div>
    </div>
</div>

resources/views/fragments/no-data.blade.php
<div class="alert alert-info" role="alert">
    No data found...
</div>