routes/web.php
<?php

use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\CampaignsController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\WebsitesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/login', [LoginController::class, 'index'])->name('login');
Route::post('/login', [LoginController::class, 'login'])->name('login-attempt');
Route::get('/register', [RegisterController::class, 'index'])->name('register');
Route::post('/register', [RegisterController::class, 'store'])->name('register-store');

Route::middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

    Route::name('websites.')->prefix('websites')->group(function () {
        Route::get('/', [WebsitesController::class, 'index'])->name('index');
        Route::get('/create', [WebsitesController::class, 'create'])->name('create');
        Route::post('/', [WebsitesController::class, 'store'])->name('store');
        Route::get('/{website}/analytics', [WebsitesController::class, 'analytics'])->name('analytics');
        Route::get('/{website}/status/{status}', [WebsitesController::class, 'status'])->name('status');
    });

    Route::name('campaigns.')->prefix('campaigns')->group(function () {
        Route::get('/', [CampaignsController::class, 'index'])->name('index');
        Route::get('/create', [CampaignsController::class, 'create'])->name('create');
        Route::post('/', [CampaignsController::class, 'store'])->name('store');
        Route::get('/{campaign}/status/{status}', [CampaignsController::class, 'status'])->name('status');
    });

    Route::name('analytics.')->prefix('analytics')->group(function () {
        Route::get('/', [AnalyticsController::class, 'index'])->name('index');
        Route::get('/{uuid}', [AnalyticsController::class, 'show'])->name('show');
    });
});

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Leetyics Dashboard</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <!-- Custom styles for this template -->
    <link href="/css/app.css" rel="stylesheet">

    @yield('header')
</head>
<body>
    <header class="navbar sticky-top bg-dark flex-md-nowrap p-0 shadow" data-bs-theme="dark">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-white" href="{{ route('dashboard') }}">Leetyics Dashboard</a>

        <ul class="navbar-nav flex-row d-md-none">
            <li class="nav-item text-nowrap">
                <button class="nav-link px-3 text-white" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="bi bi-list"></i>
                </button>
            </li>
        </ul>
    </header>

    <div class="container-fluid">
        <div class="row">
            <div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
                <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu"
                     aria-labelledby="sidebarMenuLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="sidebarMenuLabel"><a href="{{ route('dashboard') }}">Leetyics Dashboard</a></h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu"
                                aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
                        <div class="ms-3">Welcome, <strong>{{ auth()->user()->name }}</strong>!</div>

                        <hr class="my-3">

                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{{ route('dashboard') }}">
                                    <i class="bi bi-speedometer "></i> Dashboard
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link d-flex align-items-center gap-2" href="{{ route('websites.index') }}">
                                    <i class="bi bi-folder"></i> Websites
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link d-flex align-items-center gap-2" href="{{ route('campaigns.index') }}">
                                    <i class="bi bi-boxes"></i> Campaigns
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link d-flex align-items-center gap-2" href="{{ route('analytics.index') }}">
                                    <i class="bi bi-graph-up"></i> Analytics
                                </a>
                            </li>
                        </ul>

                        <hr class="my-3">

                        <ul class="nav flex-column mb-auto">
                            <li class="nav-item">
                                <a class="nav-link d-flex align-items-center gap-2" href="{{ route('logout') }}">
                                    <i class="bi bi-door-closed"></i> Sign out
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                @yield('content')
            </main>
        </div>
    </div>
<script src="/js/bootstrap.bundle.min.js"></script>
@yield('footer')

</body>
</html>