routes/web.php
<?php

use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\CampaignsController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\WebsitesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/login', [LoginController::class, 'index'])->name('login');
Route::post('/login', [LoginController::class, 'login'])->name('login-attempt');
Route::get('/register', [RegisterController::class, 'index'])->name('register');
Route::post('/register', [RegisterController::class, 'store'])->name('register-store');

Route::middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

    Route::name('websites.')->prefix('websites')->group(function () {
        Route::get('/', [WebsitesController::class, 'index'])->name('index');
        Route::get('/create', [WebsitesController::class, 'create'])->name('create');
        Route::post('/', [WebsitesController::class, 'store'])->name('store');
        Route::get('/{website}/analytics', [WebsitesController::class, 'analytics'])->name('analytics');
        Route::get('/{website}/status/{status}', [WebsitesController::class, 'status'])->name('status');
    });

    Route::name('campaigns.')->prefix('campaigns')->group(function () {
        Route::get('/', [CampaignsController::class, 'index'])->name('index');
        Route::get('/create', [CampaignsController::class, 'create'])->name('create');
        Route::post('/', [CampaignsController::class, 'store'])->name('store');
        Route::get('/{campaign}/status/{status}', [CampaignsController::class, 'status'])->name('status');
    });

    Route::name('analytics.')->prefix('analytics')->group(function () {
        Route::get('/', [AnalyticsController::class, 'index'])->name('index');
        Route::get('/{uuid}', [AnalyticsController::class, 'show'])->name('show');
    });
});

app/Models/Campaign.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Campaign extends Model
{
    use HasFactory;

    /**
     * @return BelongsTo
     */
    public function website(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Website::class);
    }
}

app/Http/Controllers/CampaignsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CampaignStoreRequest;
use App\Models\Campaign;
use App\Models\Website;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Foundation\Application;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class CampaignsController extends Controller
{
    /**
     * @return View|Application|Factory|\Illuminate\Contracts\Foundation\Application
     */
    public function index(): View|Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $sectionTitle = 'Campaigns';

        $campaigns = Campaign::where('user_id', Auth::id())
            ->orderBy('created_at', 'desc')
            ->paginate(15);

        return view('campaigns.index')
            ->with('campaigns', $campaigns)
            ->with('sectionTitle', $sectionTitle);
    }

    /**
     * @return View|Application|Factory|\Illuminate\Contracts\Foundation\Application
     */
    public function create(): View|Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $sectionTitle = 'Campaigns - Create';

        $websites = Website::where('user_id', Auth::id())
            ->orderBy('name', 'asc')
            ->get();

        return view('campaigns.create')
            ->with('websites', $websites)
            ->with('sectionTitle', $sectionTitle);
    }

    /**
     * @param CampaignStoreRequest $request
     * @return RedirectResponse
     */
    public function store(CampaignStoreRequest $request): RedirectResponse
    {
        $campaign = new Campaign();
        $campaign->user_id = Auth::id();
        $campaign->name = $request->name;
        $campaign->website_id = $request->website_id;
        $campaign->uuid = Str::uuid();
        $campaign->description = $request->description;
        $campaign->save();

        return redirect()->route('campaigns.index')
            ->with('success', 'You have successfully created new campaign.');
    }

    /**
     * @param Campaign $campaign
     * @param $status
     * @return RedirectResponse
     */
    public function status(Campaign $campaign, $status): RedirectResponse
    {
        if($campaign->user_id != Auth::id()) {
            abort(403);
        }

        if(!in_array($status, ['start', 'stop'])) {
            return redirect()->back()->with('error', 'Wrong status!');
        }

        $campaign->is_active = $status == 'start';
        $campaign->save();

        return redirect()->route('campaigns.index')->with('success', "Status has been successfully updated.");
    }
}

resources/views/campaigns/create.blade.php
@extends('layouts.master')

@section('content')
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ $sectionTitle }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a href="{{ route('campaigns.index') }}" class="btn btn-sm btn-secondary"><i class="bi bi-arrow-left-short"></i> Go Back</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-sm-12">
            @include('fragments.alerts')

            <form name="createCampaign" method="POST" action="{{ route('campaigns.store') }}">
                @csrf
                <div class="mb-3">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" name="name" class="form-control" id="name" placeholder="Campaign Name" value="{{ old('name') }}">
                </div>

                <div class="mb-3">
                    <label for="website_id" class="form-label">Website</label>
                    <select name="website_id" id="website_id" class="form-select" aria-label="Default select example">
                        <option selected>Select...</option>
                        @foreach($websites as $website)
                            <option value="{{ $website->id }}"
                                @if(old('website_id') == $website->id)
                                    selected
                                @endif
                            >{{ $website->name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="mb-3">
                    <label for="description" class="form-label">Description</label>
                    <textarea class="form-control" name="description" id="description" rows="3">{{ old('description') }}</textarea>
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-primary"><i class="bi bi-floppy"></i> Create</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/campaigns/index.blade.php
@extends('layouts.master')

@section('content')
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ $sectionTitle }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a href="{{ route('campaigns.create') }}" class="btn btn-sm btn-secondary"><i class="bi bi-folder-plus"></i> Create</a>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        @if(count($campaigns) > 0)
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Created At</th>
                    <th scope="col">Status</th>
                    <th scope="col">Name</th>
                    <th scope="col">Website</th>
                    <th scope="col">UUID</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                @foreach($campaigns as $campaign)
                    <tr>
                        <td>{{ \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $campaign->created_at)->format('d/m/Y H:i') }}</td>
                        <td>
                            @if($campaign->is_active)
                                <a href="/campaigns/{{ $campaign->id }}/status/stop" class="btn btn-sm btn-danger"><i class="bi bi-stop-circle"></i> Stop</a>
                            @else
                                <a href="/campaigns/{{ $campaign->id }}/status/start" class="btn btn-sm btn-primary"><i class="bi bi-play-fill"></i> Start</a>
                            @endif
                        </td>
                        <td>{{ $campaign->name }}</td>
                        <td><a target="_blank" href="{{ $campaign->website->url }}">{{ $campaign->website->url }}</a></td>
                        <td>{{ $campaign->uuid }}</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Controls">
                                <button data-bs-toggle="modal" data-bs-target="#modal-{{ $campaign->id }}" class="btn btn-sm btn-success"><i class="bi bi-code-square"></i> Get Code</button>
                                <a href="/analytics?website_id={{ $campaign->website_id }}&campaign_id={{ $campaign->id }}" class="btn btn-sm btn-warning"><i class="bi bi-clipboard-data"></i> Analytics</a>
                            </div>
                        </td>
                    </tr>

                    <div id="modal-{{ $campaign->id }}" class="modal" tabindex="-1">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Tracking Code</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <textarea rows="3" class="form-control" readonly>{{ $campaign->website->url . '?campaign=' . $campaign->uuid }}</textarea>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="bi bi-x-circle"></i> Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
                </tbody>
            </table>

            {{ $campaigns->links() }}
        @else
            @include('fragments.no-data')
        @endif
    </div>
@endsection